question_data = [{"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "A group of islands is called an &#039;archipelago&#039;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Gumbo is a stew that originated in Louisiana.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Art", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy", "question": "An atom contains a nucleus.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Denmark has a monarch.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Comics", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Deadpool&#039;s identity is Slade Wilson.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "According to Greek Mythology, Atlas was an Olympian God.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Scatman John&#039;s real name was John Paul Larkin.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "In Chobits, Hideki found Chii in his apartment.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Nova Scotia is on the east coast of Canada.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
